### ISSUE TITLE
Repeated attempts to download ${jar} probably because it can't be processed

### ISSUE THREAD

**Issue by jpasski** [eclipsesource/oomph#5] opened 2016-05-24 19:27 UTC
I'm attempting to install the EclipseSource Oomph profile, as outline [here](http://eclipsesource.com/blogs/2015/08/17/introducing-the-eclipsesource-oomph-profile/). However, I'm getting numerous "Repeated attempts to download ${jar} probably because it can't be processed" errors:

```
Executing bootstrap tasks
Java(TM) SE Runtime Environment 1.8.0_91-b14
Product user.products.eclipsesource.mars
Bundle org.eclipse.oomph.setup 1.4.0.v20160428-0807, build=2375, branch=897bc855cb15c9157265d77d77502211842088b5
Bundle org.eclipse.oomph.setup.core 1.4.0.v20160518-1301, build=2401, branch=f2bc94e1fe57fa62017b45cc4c34f7f4f229b59d
Bundle org.eclipse.oomph.setup.installer 1.4.0.v20160522-0658, build=2412, branch=522ddf7c504fe0fc06097a9ce6ac61e300df5e08
Bundle org.eclipse.oomph.setup.p2 1.4.0.v20160518-1301, build=2401, branch=f2bc94e1fe57fa62017b45cc4c34f7f4f229b59d
Performing P2 Director (Modeling Edition)
Offline = false
Mirrors = true
Resolving 23 requirements from 9 repositories to /Users/jonpasski/eclipse-oomph/eclipsesource-mars2/Eclipse.app/Contents/Eclipse
Requirement epp.package.modeling [4.5.2,5.0.0)
Requirement org.eclipse.platform.feature.group [4.5.2,5.0.0)
Requirement org.eclipse.rcp.feature.group [4.5.2,5.0.0)
Requirement org.eclipse.jdt.feature.group [3.11.2,4.0.0)
Requirement org.eclipse.pde.feature.group [3.11.2,4.0.0)
Requirement com.mountainminds.eclemma.feature.feature.group
Requirement net.sf.eclipsecs.feature.group
Requirement org.eclipse.rap.tools.feature.feature.group
Requirement org.eclipse.pde.api.tools.ee.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.pitest.pitclipse.feature.feature.group
Requirement com.wuetherich.osgi.ds.annotations.feature.feature.group
Requirement org.eclipse.emf.ecp.view.section.feature.source.feature.group
Requirement org.eclipse.emf.ecp.view.viewproxy.feature.source.feature.group
Requirement org.eclipse.emf.ecp.view.indexdmr.feature.source.feature.group
Requirement org.eclipse.emf.ecp.view.keyattributedmr.feature.source.feature.group
Requirement org.eclipse.emf.ecp.view.mappingdmr.feature.source.feature.group
Requirement org.eclipse.emfforms.view.annotation.feature.source.feature.group
Requirement org.eclipse.emfforms.editor.feature.source.feature.group
Requirement org.eclipse.xtend.sdk.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Repository http://download.eclipse.org/releases/mars
Repository http://download.eclipse.org/technology/epp/packages/mars
Repository http://download.eclipse.org/ecp/releases/releases_target_18
Repository http://download.eclipse.org/rt/rap/tools/3.0
Repository http://eclipse-cs.sf.net/update
Repository http://eclipse.pitest.org/release
Repository http://update.eclemma.org
Repository http://www.wuetherich.com/ds-annotations/update
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://www.wuetherich.com/ds-annotations/update
Adding repository http://update.eclemma.org
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/releases/mars
Adding repository http://download.eclipse.org/ecp/releases/releases_target_18
Adding repository http://download.eclipse.org/rt/rap/tools/3.0
Adding repository http://download.eclipse.org/technology/epp/packages/mars
Adding repository http://eclipse.pitest.org/release
Adding repository http://eclipse-cs.sf.net/update
Calculating requirements and dependencies.
Computing prerequisite plan
Collecting 0 artifacts from http://download.eclipse.org/edapt/releases/11x
Collected 0 artifacts from http://download.eclipse.org/edapt/releases/11x in 0s
Collecting 0 artifacts from http://www.wuetherich.com/ds-annotations/update
Collected 0 artifacts from http://www.wuetherich.com/ds-annotations/update in 0s
Collecting 0 artifacts from http://download.eclipse.org/oomph/updates/milestone/latest
Collected 0 artifacts from http://download.eclipse.org/oomph/updates/milestone/latest in 0s
Collecting 8 artifacts from http://download.eclipse.org/releases/mars
Downloading epp.package.modeling.executable.cocoa.macosx.x86_64
Downloading org.eclipse.amalgam.discovery_root
Downloading org.eclipse.platform_root
Downloading org.eclipse.emf.ecoretools.design_root
Downloading org.eclipse.emf.ecp.license.feature_root
Downloading org.eclipse.platform.ide.executable.cocoa.macosx.x86_64
Downloading org.eclipse.emf.emfstore.license.feature_root
Downloading org.eclipse.rcp_root
Collected 8 artifacts from http://download.eclipse.org/releases/mars in 1.2s
Collecting 0 artifacts from http://eclipse.pitest.org/release
Collected 0 artifacts from http://eclipse.pitest.org/release in 0.001s
Collecting 0 artifacts from http://download.eclipse.org/tools/orbit/downloads/drops/R20150821153341/repository/
Collected 0 artifacts from http://download.eclipse.org/tools/orbit/downloads/drops/R20150821153341/repository/ in 0.242s
Collecting 0 artifacts from http://update.eclemma.org
Collected 0 artifacts from http://update.eclemma.org in 0.001s
Collecting 54 artifacts from http://download.eclipse.org/ecp/releases/releases_target_18
Downloading org.eclipse.emf.ecp.view.indexdmr.tooling
Downloading org.eclipse.emfforms.core.services.structuralchange.index.source
Downloading org.eclipse.emf.ecp.view.indexdmr.tooling.source
Downloading org.eclipse.emfforms.core.services.structuralchange.mapping.source
Downloading org.eclipse.emfforms.core.services.domainexpander.index.source
Downloading org.eclipse.emfforms.core.services.domainexpander.mapping.source
Downloading org.eclipse.emfforms.core.services.databinding.mapping.source
Downloading org.eclipse.emf.ecp.view.keyattributedmr.model.edit
Downloading org.eclipse.emfforms.view.annotation.model.edit
Downloading org.eclipse.emfforms.view.annotation.model
Repeated attempts to download http://eclipse.mirror.rafal.ca/ecp/releases/releases_17/plugins/org.eclipse.emf.ecp.view.indexdmr.tooling.source_1.8.0.20160216-1319.jar probably because it can't be processed
Repeated attempts to download http://mirror.ibcp.fr/pub/eclipse//ecp/releases/releases_17/plugins/org.eclipse.emf.ecp.view.keyattributedmr.model.edit_1.8.0.20160216-1319.jar.pack.gz probably because it can't be processed
Repeated attempts to download http://mirror.ibcp.fr/pub/eclipse//ecp/releases/releases_17/plugins/org.eclipse.emf.ecp.view.indexdmr.tooling_1.8.0.20160216-1319.jar.pack.gz probably because it can't be processed
Repeated attempts to download http://eclipse.mirror.rafal.ca/ecp/releases/releases_17/plugins/org.eclipse.emf.ecp.view.indexdmr.tooling.source_1.8.0.20160216-1319.jar probably because it can't be processed
Repeated attempts to download http://eclipse.mirror.rafal.ca/ecp/releases/releases_17/plugins/org.eclipse.emfforms.core.services.databinding.mapping.source_1.8.0.20160216-1319.jar probably because it can't be processed
...
```

This continues ad infinitum until the Oomph install is stopped.

**Comment by aumann** [comment] 2016-06-08 09:57
I see a very similar issue (also with ecp resources):
`Repeated attempts to download http://mirror.switch.ch/eclipse/ecp/releases/releases_15/150/plugins/org.eclipse.emf.ecp.emfstore.core.rap_1.7.2.20151117-1207.jar.pack.gz probably because it can't be processed`

The strange thing is that the repository address version does not seem to match the version to be downloaded.

**Comment by JonasHelming** [comment] 2016-06-08 15:36
Hi,

I have just tested a plain installation, and did not get any error. We fixed a related one yesterday.
Could you kindly retry and let me know, if the problem still persits?

Thanks

**Comment by aumann** [comment] 2016-06-09 09:05
Hi,
I believe the problem persists. I am using the repository at:
`http://download.eclipse.org/ecp/releases/releases_target_17`
for targlet provisioning.

When I have mirrors activated the above message appears endlessly. Deactivating mirrors and restarting everything did work, though.

**Comment by JonasHelming** [comment] 2016-06-09 10:24
OK, so the problem is not there, if you use the standard Oomph Profile, but you have added a custom targlet?

**Comment by aumann** [comment] 2016-06-09 14:23
Yes, there is a custom targlet. It works even with this targlet but only if I deactivate mirrors.

**Comment by JonasHelming** [comment] 2016-06-09 14:32
OK, in this case, this is more related to either the Eclipse mirroring or to Oomph itself, but not to our generic profile, right? I would then close this BR

**Comment by aumann** [comment] 2016-06-10 08:31
I probably posted this at the wrong place to start with - just based on the similar error messages.

**Comment by JonasHelming** [comment] 2016-06-10 09:44
@jonpasski : Is your issue still relevant?

**Comment by JonasHelming** [comment] 2016-06-10 09:45
please reopen if so...

**Closed as completed by JonasHelming** 2016-06-10 09:45 UTC

**Comment by jpasski** [comment] 2016-06-12 16:49
Performing the same steps with the latest Oomph installer now works for me, thanks!

**Comment by TheMasterRoot** [comment] 2016-07-11 17:32
im facing the same insue whit new version
![image](https://cloud.githubusercontent.com/assets/7121027/16740204/4f22c9da-4774-11e6-8e24-8f7afbc13e58.png)

**Comment by JonasHelming** [comment] 2016-07-12 07:27
Can you restest after a while? Which version are you trying to install?

**Comment by englandt** [comment] 2016-07-15 21:39
![image](https://cloud.githubusercontent.com/assets/16090187/16889242/d8cc8f04-4a99-11e6-9bdd-0d6e1ea9513a.png)

Having the same issue here with Eclipse Java EE.

**Comment by JonasHelming** [comment] 2016-07-18 12:08
Sorry to say, but this project is actually about the EclipseSource Profiler, not about general problems with the Eclipse Installer, I am closing this...

**Comment by Srishgoyal** [comment] 2019-06-21 14:52
Hi, I am facing this issue for all the eclipse versions i am trying to install. Is there any solution to this issue available?

**Comment by JonasHelming** [comment] 2019-06-25 20:37
Are you using the EclipseSource Oomph Profile or just trying to install any Eclipse version?
